"""Shared runtime ports for transport, peripherals and state observation."""

from __future__ import annotations

from typing import Any, Callable, Protocol

from device_runtime.domain.capabilities import DeviceCapabilities
from device_runtime.domain.state import DeviceSnapshot


class TransportPort(Protocol):
    async def connect(self) -> None: ...

    async def send(self, message: dict[str, Any]) -> None: ...

    def set_message_handler(self, handler: Callable[[dict[str, Any]], None]) -> None: ...

    def set_connection_handler(self, handler: Callable[[str, str | None], None]) -> None: ...

    async def close(self) -> None: ...


class DisplayPort(Protocol):
    def render(self, model: Any) -> None: ...

    def show_diagnostic(self, line: str) -> None: ...


class ButtonInputPort(Protocol):
    def start(self, on_event: Callable[[str], None]) -> None: ...

    def stop(self) -> None: ...


class AudioCapturePort(Protocol):
    def start(self) -> None: ...

    def stop(self) -> None: ...

    def read_chunks(self, max_chunks: int) -> list[dict[str, Any]]: ...

    @property
    def available(self) -> bool: ...


class AudioPlaybackPort(Protocol):
    def start(self, sample_rate: int, channels: int) -> None: ...

    def push(self, pcm_bytes: bytes) -> None: ...

    def stop(self, clear_buffer: bool = True) -> None: ...

    @property
    def available(self) -> bool: ...


class DiagnosticsPort(Protocol):
    def record(self, event: str, **data: Any) -> None: ...


class CapabilityProvider(Protocol):
    def detect(self) -> DeviceCapabilities: ...


class BackendGateway(Protocol):
    async def start_listen(self, turn_id: str) -> None: ...

    async def stop_listen(self, turn_id: str) -> None: ...

    async def cancel_listen(self, turn_id: str | None) -> None: ...

    async def send_audio_chunk(self, turn_id: str, chunk: dict[str, Any]) -> None: ...

    async def request_agents_version(self) -> None: ...

    async def request_agents_list(self) -> None: ...

    async def confirm_agent(self, agent_id: str) -> None: ...


class Clock(Protocol):
    def now(self) -> float: ...


class StateObserver(Protocol):
    def publish(self, snapshot: DeviceSnapshot) -> None: ...
